pragma Singleton
import QtQuick

QtObject {
    // ============================================================================
    // BASE PALETTE - Zinc Scale
    // ============================================================================
    // These are your neutral colors - when using matugen, these won't be used
    // directly but are here for manual theming fallback
    
    readonly property color zinc50: "#fafafa"
    readonly property color zinc100: "#f4f4f5"
    readonly property color zinc200: "#e4e4e7"
    readonly property color zinc300: "#d4d4d8"
    readonly property color zinc400: "#a1a1aa"
    readonly property color zinc500: "#71717a"
    readonly property color zinc600: "#52525b"
    readonly property color zinc700: "#3f3f46"
    readonly property color zinc800: "#27272a"
    readonly property color zinc900: "#18181b"
    readonly property color zinc950: "#09090b"
    
    // ============================================================================
    // MATUGEN SEMANTIC TOKENS (Material Design 3)
    // ============================================================================
    // These values are generated by matugen from your wallpaper
    
    // --- Primary Colors (Main brand color) ---
    readonly property color primary: "#86d1ea"
    readonly property color on_primary: "#003642"
    readonly property color primary_container: "#004e5f"
    readonly property color on_primary_container: "#b3ebff"
    readonly property color primary_fixed: "#b3ebff"
    readonly property color primary_fixed_dim: "#86d1ea"
    readonly property color on_primary_fixed: "#001f27"
    readonly property color on_primary_fixed_variant: "#004e5f"
    
    // --- Secondary Colors (Supporting color) ---
    readonly property color secondary: "#b3cad4"
    readonly property color on_secondary: "#1d333b"
    readonly property color secondary_container: "#344a52"
    readonly property color on_secondary_container: "#cee6f0"
    readonly property color secondary_fixed: "#cee6f0"
    readonly property color secondary_fixed_dim: "#b3cad4"
    readonly property color on_secondary_fixed: "#061e25"
    readonly property color on_secondary_fixed_variant: "#344a52"
    
    // --- Tertiary Colors (Third accent) ---
    readonly property color tertiary: "#c1c4eb"
    readonly property color on_tertiary: "#2b2e4d"
    readonly property color tertiary_container: "#414465"
    readonly property color on_tertiary_container: "#dfe0ff"
    readonly property color tertiary_fixed: "#dfe0ff"
    readonly property color tertiary_fixed_dim: "#c1c4eb"
    readonly property color on_tertiary_fixed: "#151937"
    readonly property color on_tertiary_fixed_variant: "#414465"
    
    // --- Error Colors ---
    readonly property color error: "#ffb4ab"
    readonly property color on_error: "#690005"
    readonly property color error_container: "#93000a"
    readonly property color on_error_container: "#ffdad6"
    
    // --- Background Colors ---
    readonly property color background: "#0f1416"
    readonly property color on_background: "#dee3e6"
    
    // --- Surface Colors (5-level elevation system) ---
    readonly property color surface: "#0f1416"
    readonly property color on_surface: "#dee3e6"
    readonly property color surface_variant: "#40484b"
    readonly property color on_surface_variant: "#bfc8cc"
    
    readonly property color surface_dim: "#0f1416"
    readonly property color surface_bright: "#343a3c"
    readonly property color surface_container_lowest: "#0a0f11"
    readonly property color surface_container_low: "#171c1f"
    readonly property color surface_container: "#1b2023"
    readonly property color surface_container_high: "#252b2d"
    readonly property color surface_container_highest: "#303638"
    
    // --- Outline Colors (Borders) ---
    readonly property color outline: "#899296"
    readonly property color outline_variant: "#40484b"
    
    // --- Inverse Colors (for dark/light theme switching) ---
    readonly property color inverse_surface: "#dee3e6"
    readonly property color inverse_on_surface: "#2c3133"
    readonly property color inverse_primary: "#02677d"
    
    // --- Scrim & Shadow ---
    readonly property color scrim: "#000000"
    readonly property color shadow: "#000000"
    
    // ============================================================================
    // SPACING SYSTEM
    // ============================================================================
    
    readonly property QtObject spacing: QtObject {
        readonly property int xs: 4
        readonly property int sm: 8
        readonly property int md: 12
        readonly property int lg: 18
        readonly property int xl: 26 
        readonly property int xxl: 48
    }
    
    // ============================================================================
    // PADDING SYSTEM
    // ============================================================================
    
    readonly property QtObject padding: QtObject {
        readonly property int xs: 4
        readonly property int sm: 8
        readonly property int md: 12
        readonly property int lg: 18
        readonly property int xl: 20
    }
    
    // ============================================================================
    // TYPOGRAPHY SYSTEM
    // ============================================================================
    
    readonly property QtObject typography: QtObject {
        readonly property string fontFamily: "Ubuntu Nerd Font Propo"
        
        readonly property int xs: 10
        readonly property int sm: 12
        readonly property int md: 14
        readonly property int lg: 16
        readonly property int xl: 18
        readonly property int xxl: 24
        readonly property int xxxl: 32
        
        readonly property int weightNormal: 400
        readonly property int weightMedium: 500
        readonly property int weightBold: 700
    }
    
    // ============================================================================
    // SHAPE SYSTEM (Border Radius)
    // ============================================================================
    
    readonly property QtObject radius: QtObject {
        readonly property int none: 0
        readonly property int sm: 6
        readonly property int md: 12
        readonly property int lg: 20
        readonly property int xl: 32 
        readonly property int xxl: 40
        readonly property int full: 9999
    }
    
    // ============================================================================
    // COMPONENT TOKENS
    // ============================================================================
    
    readonly property QtObject component: QtObject {
        readonly property int barHeight: 26
        readonly property int workspaceIndicatorSize: 10
        readonly property int buttonHeight: 36
        readonly property int inputHeight: 40
    }
    
    // ============================================================================
    // LEGACY ALIASES (for backward compatibility)
    // ============================================================================
    // These allow your existing code to work without changes
    
    readonly property color accent: primary
    readonly property color accentFixed: primary_fixed
    readonly property color bg0: surface
    readonly property color bg1: surface_container
    readonly property color bg1transparent: surface_container_transparent
    readonly property color bg2: surface_container_low
    readonly property color bgBright: surface_bright
    readonly property color bgDim: surface_dim
    readonly property color fg: on_surface
    readonly property color fgStrong: on_surface
    readonly property color fgMuted: on_surface_variant
    readonly property color border: outline
    readonly property color borderStrong: primary
    readonly property color borderDim: outline_variant
    
    // Spacing aliases
    readonly property int spacingXSmall: spacing.xs
    readonly property int spacingSmall: spacing.sm
    readonly property int spacingMedium: spacing.md
    readonly property int spacingLarge: spacing.lg
    readonly property int spacingXLarge: spacing.xl
    readonly property int spacingXS: spacing.xs
    readonly property int spacingS: spacing.sm
    readonly property int spacingM: spacing.md
    readonly property int spacingL: spacing.lg
    readonly property int spacingXL: spacing.xl
    
    // Margin aliases
    readonly property int marginXSmall: padding.xs
    readonly property int marginSmall: padding.sm
    readonly property int marginMedium: padding.md
    readonly property int marginLarge: padding.lg
    readonly property int marginXLarge: padding.xl
    readonly property int marginXS: padding.xs
    readonly property int marginS: padding.sm
    readonly property int marginM: padding.md
    readonly property int marginL: padding.lg
    readonly property int marginXL: padding.xl
    
    // Font aliases
    readonly property string fontFamily: typography.fontFamily
    readonly property int fontSizeXSmall: typography.xs
    readonly property int fontSizeSmall: typography.sm
    readonly property int fontSizeMedium: typography.md
    readonly property int fontSizeLarge: typography.lg
    readonly property int fontSizeXLarge: typography.xl
    readonly property int fontSizeXS: typography.xs
    readonly property int fontSizeS: typography.sm
    readonly property int fontSizeM: typography.md
    readonly property int fontSizeL: typography.lg
    readonly property int fontSizeXL: typography.xl
    
    // Radius aliases
    readonly property int radiusSmall: radius.sm
    readonly property int radiusMedium: radius.md
    readonly property int radiusLarge: radius.lg
    readonly property int radiusXLarge: radius.xl
    
    // Component aliases
    readonly property int barHeight: component.barHeight
    readonly property int workspaceIndicatorSize: component.workspaceIndicatorSize
}
